import img from "./assets/image1.png";
import img1 from "./assets/image2.png";

export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 2000,
  },
  {
    name: "Apr",
    "Active User": 2780,
  },
  {
    name: "May",
    "Active User": 1890,
  },
  {
    name: "Jun",
    "Active User": 2390,
  },
  {
    name: "Jul",
    "Active User": 3490,
  },
  {
    name: "Aug",
    "Active User": 5490,
  },
  {
    name: "Sept",
    "Active User": 2300,
  },
  {
    name: "Oct",
    "Active User": 4490,
  },
  {
    name: "Nov",
    "Active User": 1490,
  },
  {
    name: "Dec",
    "Active User": 3490,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 11,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 12,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 13,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 14,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 15,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 16,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 17,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 18,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 19,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 20,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 21,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 22,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 23,
    username: "Jon Snow",
    avatar: `${img}`,
    email: "johnsnow@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 2,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 3,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 4,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 6,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 7,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 8,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 9,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
  {
    id: 10,
    name: "Apple Airpods",
    img: `${img1}`,
    stock: 123,
    status: "active",
    price: "$120.00",
  },
];
